### ISSUE TITLE
Font files do not install correctly on my display

### ISSUE THREAD

**Issue by adam3654** [Quint097/DWIN_Font_Files#2]
None of the three HZK files install correctly on my display

**To Reproduce**
1. Format SD card 8GB, 4096KB
2. Add folder named 'DWIN_SET'
3. copy HZK file to folder
4. insert in SD slot of Display
5. power on printer
6. wait for blue->orange screen
7. power off printer
8. remove SD card from back of display
9. power on printer and see garbled font

**Expected behavior**
See font displaying correctly

**Screenshots**
![PXL_20210618_051322488_2](https://user-images.githubusercontent.com/16920869/122588402-0f13e580-d02d-11eb-906d-c22a7dce9b2f.jpg)

**Printer (please complete the following information):**
- Ender 3 V2 
- Jyers Latest Commit with minor tweaks
- Version 1.3.4

**Additional context**
The original font file [Found Here](https://e.pcloud.link/publink/show?code=XZItmVZI9fpiycqstQrkWiTQJcn6pnt5tFk) was the only way to get the font back to normal

**Comment by adam3654** [comment]
The zip file provided in the [Jyers discussion](https://github.com/Jyers/Marlin/discussions/953) worked. 
Has anyone else tried the font files directly from the repo? Is this just a 'me' problem?

**Comment by Quint097** [comment]
> Has anyone else tried the font files directly from the repo? Is this just a 'me' problem?

I have had people who had problems cloning my repo before. I thought it had to do with the points in the folder names. But now there remove, it seems that wasn't it.

**Comment by Quint097** [comment]
I have added a zip file containing the most recent fonts to the repo. and update the README.md. This should solve the problem for you and anyone else with this problem.

let me know if there is anything else I can help with, otherwise you can close this issue.

**Comment by adam3654** [comment]
Thank you! The ability to switch fonts is so cool. It was something I've wanted to do since I first started with custom firmware.
